const data = [
  {
    id: 0,
    name: "Bulbasaur",
    level: 0,
    hp: 10,
    sp: 10,
    attack: 5,
    type: "grass",
    weakness: [{ type: "fire", penalty: 5 }],
    powerBonus: [{ type: "water", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/001.png",
      "http://www.serebii.net/Shiny/XY/001.png",
    ],
    accuracy: 50,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 100,
  },
  {
    id: 1,
    name: "Ivysaur",
    level: 1,
    hp: 20,
    sp: 20,
    attack: 10,
    type: "grass",
    weakness: [{ type: "fire", penalty: 5 }],
    powerBonus: [{ type: "water", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/002.png",
      "http://www.serebii.net/Shiny/XY/002.png",
    ],
    accuracy: 70,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 200,
  },
  {
    id: 2,
    name: "Venusaur",
    level: 2,
    hp: 50,
    sp: 50,
    attack: 30,
    type: "grass",
    weakness: [{ type: "fire", penalty: 5 }],
    powerBonus: [{ type: "water", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/003.png",
      "http://www.serebii.net/Shiny/XY/003.png",
    ],
    accuracy: 90,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 3,
    name: "Charmander",
    level: 0,
    hp: 10,
    sp: 10,
    attack: 5,
    type: "fire",
    weakness: [{ type: "water", penalty: 5 }],
    powerBonus: [{ type: "grass", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/004.png",
      "http://www.serebii.net/Shiny/XY/004.png",
    ],
    accuracy: 50,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 100,
  },
  {
    id: 4,
    name: "Charmeleon",
    level: 1,
    hp: 20,
    sp: 20,
    attack: 10,
    type: "fire",
    weakness: [{ type: "water", penalty: 5 }],
    powerBonus: [{ type: "grass", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/005.png",
      "http://www.serebii.net/Shiny/XY/005.png",
    ],
    accuracy: 70,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 200,
  },
  {
    id: 5,
    name: "Charizard ",
    level: 2,
    hp: 50,
    sp: 50,
    attack: 30,
    type: "fire",
    weakness: [{ type: "water", penalty: 5 }],
    powerBonus: [{ type: "grass", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/006.png",
      "http://www.serebii.net/Shiny/XY/006.png",
    ],
    accuracy: 90,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 6,
    name: "Squirtle",
    level: 0,
    hp: 10,
    sp: 10,
    attack: 5,
    type: "water",
    weakness: [{ type: "grass", penalty: 5 }],
    powerBonus: [{ type: "fire", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/007.png",
      "http://www.serebii.net/Shiny/XY/007.png",
    ],
    accuracy: 50,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 100,
  },
  {
    id: 7,
    name: "Wartortle",
    level: 1,
    hp: 20,
    sp: 20,
    attack: 10,
    type: "water",
    weakness: [{ type: "grass", penalty: 5 }],
    powerBonus: [{ type: "fire", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/008.png",
      "http://www.serebii.net/Shiny/XY/008.png",
    ],
    accuracy: 70,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 200,
  },
  {
    id: 8,
    name: "Blastoise",
    level: 2,
    hp: 50,
    sp: 50,
    attack: 30,
    type: "water",
    weakness: [{ type: "grass", penalty: 5 }],
    powerBonus: [{ type: "fire", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/009.png",
      "http://www.serebii.net/Shiny/XY/009.png",
    ],
    accuracy: 90,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 9,
    name: "Pikachu",
    level: 0,
    hp: 10,
    sp: 10,
    attack: 5,
    type: "electric",
    weakness: [{ type: "grass", penalty: 5 }],
    powerBonus: [{ type: "water", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/025.png",
      "http://www.serebii.net/Shiny/XY/025.png",
    ],
    accuracy: 50,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 150,
  },
  {
    id: 10,
    name: "Raichu",
    level: 1,
    hp: 20,
    sp: 20,
    attack: 10,
    type: "electric",
    weakness: [{ type: "grass", penalty: 5 }],
    powerBonus: [{ type: "water", bonus: 5 }],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/026.png",
      "http://www.serebii.net/Shiny/XY/026.png",
    ],
    accuracy: 70,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 11,
    name: "Mew",
    level: 100,
    hp: 5000,
    sp: 5000,
    attack: 5000,
    type: "mystic",
    weakness: [],
    powerBonus: [],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/151.png",
      "http://www.serebii.net/Shiny/XY/151.png",
    ],
    accuracy: 100,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 12,
    name: "Mewtwo",
    level: Infinity,
    hp: Infinity,
    sp: Infinity,
    attack: Infinity,
    type: "mystic",
    weakness: [],
    powerBonus: [],
    imgUrl: [
      "http://www.serebii.net/xy/pokemon/150.png",
      "http://www.serebii.net/Shiny/XY/150.png",
    ],
    accuracy: 100,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
];
