const data = [
  {
    id: 0,
    name: "tree",
    level: Infinity,
    hp: Infinity,
    sp: Infinity,
    attack: {
      power: Infinity,
      weakness: { type: null, penalty: 1 },
      bonus: { type: null, powerBonus: 1 },
    },
    type: null,
    img: {
      url: ["/docs/assets/imgs/trees.png", "/docs/assets/imgs/trees.png"],
      sizeX: 50,
      sizeY: 50,
    },
    accuracy: 100,
    attackImg: null,
    evolve: false,
    evolveScore: null,
  },
  {
    id: 1,
    name: "Bulbasaur",
    level: 1,
    hp: 10,
    sp: 10,
    attack: {
      power: 5,
      weakness: { type: "fire", penalty: 0.8 },
      bonus: { type: "water", powerBonus: 1.5 },
    },
    type: "grass",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/001.png",
        "http://www.serebii.net/Shiny/XY/001.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 50,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 100,
  },
  {
    id: 2,
    name: "Ivysaur",
    level: 2,
    hp: 20,
    sp: 20,
    attack: {
      power: 10,
      weakness: { type: "fire", penalty: 0.8 },
      bonus: { type: "water", powerBonus: 1.5 },
    },
    type: "grass",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/002.png",
        "http://www.serebii.net/Shiny/XY/002.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 70,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 300,
  },
  {
    id: 3,
    name: "Venusaur",
    level: 3,
    hp: 50,
    sp: 50,
    attack: {
      power: 30,
      weakness: { type: "fire", penalty: 0.8 },
      bonus: { type: "water", powerBonus: 1.5 },
    },
    type: "grass",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/003.png",
        "http://www.serebii.net/Shiny/XY/003.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 90,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 4,
    name: "Charmander",
    level: 1,
    hp: 10,
    sp: 10,
    attack: {
      power: 5,
      weakness: { type: "water", penalty: 0.8 },
      bonus: { type: "grass", powerBonus: 1.5 },
    },
    type: "fire",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/004.png",
        "http://www.serebii.net/Shiny/XY/004.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 50,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 100,
  },
  {
    id: 5,
    name: "Charmeleon",
    level: 2,
    hp: 20,
    sp: 20,
    attack: {
      power: 10,
      weakness: { type: "water", penalty: 0.8 },
      bonus: { type: "grass", powerBonus: 1.5 },
    },
    type: "fire",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/005.png",
        "http://www.serebii.net/Shiny/XY/005.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 70,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 300,
  },
  {
    id: 6,
    name: "Charizard ",
    level: 3,
    hp: 50,
    sp: 50,
    attack: {
      power: 30,
      weakness: { type: "water", penalty: 0.8 },
      bonus: { type: "grass", powerBonus: 1.5 },
    },
    type: "fire",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/006.png",
        "http://www.serebii.net/Shiny/XY/006.png",
      ],
      sizeX: 137,
      sizeY: 120,
    },
    accuracy: 90,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 7,
    name: "Squirtle",
    level: 1,
    hp: 10,
    sp: 10,
    attack: {
      power: 5,
      weakness: { type: "grass", penalty: 0.8 },
      bonus: { type: "fire", powerBonus: 1.5 },
    },
    type: "water",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/007.png",
        "http://www.serebii.net/Shiny/XY/007.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 50,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 100,
  },
  {
    id: 8,
    name: "Wartortle",
    level: 2,
    hp: 20,
    sp: 20,
    attack: {
      power: 10,
      weakness: { type: "grass", penalty: 0.8 },
      bonus: { type: "fire", powerBonus: 1.5 },
    },
    type: "water",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/008.png",
        "http://www.serebii.net/Shiny/XY/008.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 70,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 300,
  },
  {
    id: 9,
    name: "Blastoise",
    level: 3,
    hp: 50,
    sp: 50,
    attack: {
      power: 30,
      weakness: { type: "grass", penalty: 0.8 },
      bonus: { type: "fire", powerBonus: 1.5 },
    },
    type: "water",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/009.png",
        "http://www.serebii.net/Shiny/XY/009.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 90,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 10,
    name: "Pikachu",
    level: 1,
    hp: 10,
    sp: 10,
    attack: {
      power: 5,
      weakness: { type: "grass", penalty: 0.8 },
      bonus: { type: "water", powerBonus: 1.5 },
    },
    type: "electric",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/025.png",
        "http://www.serebii.net/Shiny/XY/025.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 50,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: true,
    evolveScore: 150,
  },
  {
    id: 11,
    name: "Raichu",
    level: 2,
    hp: 20,
    sp: 20,
    attack: {
      power: 10,
      weakness: { type: "grass", penalty: 0.8 },
      bonus: { type: "water", powerBonus: 1.5 },
    },
    type: "electric",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/026.png",
        "http://www.serebii.net/Shiny/XY/026.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 70,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 12,
    name: "Mew",
    level: 100,
    hp: 5000,
    sp: 5000,
    attack: {
      power: 5000,
      weakness: { type: null, penalty: 1 },
      bonus: { type: null, powerBonus: 1 },
    },
    type: "mystic",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/151.png",
        "http://www.serebii.net/Shiny/XY/151.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 100,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
  {
    id: 13,
    name: "Mewtwo",
    level: Infinity,
    hp: Infinity,
    sp: Infinity,
    attack: {
      power: Infinity,
      weakness: { type: null, penalty: 1 },
      bonus: { type: null, powerBonus: 1 },
    },
    type: "mystic",
    img: {
      url: [
        "http://www.serebii.net/xy/pokemon/150.png",
        "http://www.serebii.net/Shiny/XY/150.png",
      ],
      sizeX: 120,
      sizeY: 120,
    },
    accuracy: 100,
    attackImg: "/docs/assets/imgs/fire-ball.png",
    evolve: false,
    evolveScore: null,
  },
];
